### ISSUE TITLE
/docs/Web/HTML/Element/abbr fails because there are no attributes

### ISSUE THREAD

**Issue by peterbe** [peterbe/mdn2#13]
```
▶ cat stumptown/packaged/html/elements/abbr.json | jq .html.elements.attributes
null
```

This is breaking `make deployment-build` but it's not obvious where the bug lies. In Stumptown or in this repo's renderer business logic.

**Comment by peterbe** [comment]
<img width="629" alt="Screen Shot 2019-06-04 at 9 51 48 AM" src="https://user-images.githubusercontent.com/26739/58884429-6648f680-86ae-11e9-9279-db27caac9efa.png">

**Comment by wbamberg** [comment]
What's happening here is: `abbr` has no attributes (or rather, has only the global attributes) and in build-json that is [making us set the `attributes` property to `null`](https://github.com/mdn/stumptown-experiment/blob/master/scripts/build-json/build-page-json.js#L58). But then [mdn2 assumes that `attributes` is not `null`](https://github.com/peterbe/mdn2/blob/master/client/src/ingredients/attributes.js#L21).

There are I think a few things to fix in here:

First, stumptown should probably make `attributes` an empty array instead of `null` if there are no attributes

Second, after writing the Attributes H2, mdn2 should write some boilerplate like:

"This element supports only the [global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)." if `attributes` is empty, or

"This element supports the [global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) as well as the following element-specific attributes:" if `attributes` is not empty

Also, there's a thing in prose.md called "attributes_text": this gives authors a way to express some freeform stuff about the attributes. [In `abbr`, for example, the bit about `title`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr#Attributes) would probably take advantage of that. We ought to find a way to render this in stumptown as well.

**Comment by wbamberg** [comment]
This is fixed by https://github.com/mdn/stumptown-experiment/pull/50 and https://github.com/peterbe/mdn2/pull/14.
